#! /bin/python3
# -*- coding: Utf-8 -*

import sys
from math import sqrt, pow, acos, degrees

argv = sys.argv

def print_usage():
    print("USAGE")
    print("\t./101pong x0 y0 z0 x1 y1 z1 n\n")
    print("DESCRIPTION")
    print("\tx0  ball abscissa at time t - 1")
    print("\tx0  ball abscissa at time t - 1")
    print("\tx0  ball abscissa at time t - 1")
    print("\tx1  ball abscissa at time t")
    print("\tx1  ball abscissa at time t")
    print("\tx1  ball abscissa at time t")
    print("\tn   time shift (greater than or equal to 0)")
    exit(84)

def check_error():
    if (len(argv) != 8):
        print_usage()
    for i in range(1, 8):
        try:
            float(argv[i])
        except ValueError:
            print_usage()
    if ("." in argv[7] or float(argv[7]) < 0):
        print_usage()

def convert_args(argv):
    m0 = list()
    m1 = list()
    for loop in range(1, 4) :
        m0.append(float(argv[loop]))
    for loop in range(4, 7) :
        m1.append(float(argv[loop]))
    time = int(argv[7])
    return m0, m1, time

def calcul_velocity_vector(m0, m1):
    velocity = list()
    for i in range(3):
        velocity.append(m1[i] - m0[i])
    return velocity

def calcul_coordonates(m1, time, velocity):
    coord = list()
    for i in range(3):
        coord.append(m1[i] + (time * velocity[i]))
    return coord

def determine_angle(velocity):
    Oz_vector = [0, 0, 1]
    u = Oz_vector
    v = velocity
    vector_product = 0.0
    for i in range(3):
        vector_product += u[i] * v[i]
    u_norm = sqrt(pow(u[0], 2) + pow(u[1], 2) + pow(u[2], 2))
    v_norm = sqrt(pow(v[0], 2) + pow(v[1], 2) + pow(v[2], 2))
    angle = degrees(acos(vector_product / (u_norm * v_norm)))
    return abs(angle - 90)

#Error handling
check_error()

#Calculating velocity vector
m0, m1, time = convert_args(argv)
velocity = calcul_velocity_vector(m0, m1)
print("The velocity vector of the ball is:")
print("({0:.2f}, {1:.2f}, {2:.2f})".format(velocity[0], velocity[1], velocity[2]))

#Calculating coordonates at time n
coord = calcul_coordonates(m1, time, velocity)
print("At time t +", time, ", ball coordinates will be:")
print("({0:.2f}, {1:.2f}, {2:.2f})".format(coord[0], coord[1], coord[2]))

#Determine angle of incidence
if ((m1[2] > 0.0 and velocity[2] < 0.0) or (m1[2] < 0.0 and velocity[2] > 0.0)):
    angle = determine_angle(velocity)
    print("The incidence angle is:")
    print("{0:.2f} degrees".format(angle))
elif ((m1[2] == 0.0) and (velocity[2] == 0)):
    print("The incidence angle is:")
    print("0.00 degrees")
else:
    print("The ball won't reach the paddle.")
exit(0)
