#! /bin/python3
# -*- coding: Utf-8 -*

import sys
from pong import Pong

def main(argc, argv):
    if argc == 3:
        Pong(int(argv[1]), int(argv[2])).run()
    else:
        Pong().run()
if __name__ == "__main__":
    main(len(sys.argv), sys.argv)
